import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  userEmail = 'm.suleman@outlook.com',
  userName = 'Muhammad Suleman',
}: Readonly<{
  children: React.ReactNode;
  userEmail?: string;
  userName?: string;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex flex-col md:flex-row justify-start">
          <Sidebar userEmail={userEmail} userName={userName} />
          <main className="flex-1">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
