#!/bin/sh

pnpm fe lint
if [ $? -ne 0 ]; then
  echo "❌ Lint errors found. Please fix them before committing."
  exit 1
fi

pnpm fe format
if [ $? -ne 0 ]; then
  echo "❌ Formatting errors found. Please fix them before committing."
  exit 1
fi