#!/bin/sh

pnpm fe lint
if [ $? -ne 0 ]; then
  echo "❌ Lint errors found. Please fix them before committing."
  exit 1
fi

# Format only staged files that Prettier supports
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.(js|jsx|ts|tsx|json|css|md|yml|yaml|scss)$' || true)
if [ -n "$STAGED_FILES" ]; then
  npx prettier --write $STAGED_FILES
  git add $STAGED_FILES
fi